theme: jekyll-theme-midnight
title: [Monti Picentini Digitali]
description: [Monti Picentini Digitali è un progetto artistico nato intorno alla personale passione per la montagna, la pratica del field recording e l'arte digitale.]
